- name: Show which file is running
  run: echo "✅ Running from deploy.yml"
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        script: |
          cd ~/dockerproject2025
          git pull
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker-compose down
          docker-compose up -d
